package com.cloudbox.api.exception.cloud.auth;

/**
 * The CloudAuthException is thrown when cant validate credentials.
 */
public class CloudAuthValidationException extends RuntimeException {
}
